# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0002_auto_20160916_1342'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='membership',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='on_behalf_of',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='post',
        ),
        migrations.RemoveField(
            model_name='membershipcontactdetail',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='membershiplink',
            name='membership',
        ),
        migrations.AlterIndexTogether(
            name='organization',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='organizationcontactdetail',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationidentifier',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationlink',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationname',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationsource',
            name='organization',
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='post',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='postcontactdetail',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlink',
            name='post',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='MembershipContactDetail',
        ),
        migrations.DeleteModel(
            name='MembershipLink',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationContactDetail',
        ),
        migrations.DeleteModel(
            name='OrganizationIdentifier',
        ),
        migrations.DeleteModel(
            name='OrganizationLink',
        ),
        migrations.DeleteModel(
            name='OrganizationName',
        ),
        migrations.DeleteModel(
            name='OrganizationSource',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostContactDetail',
        ),
        migrations.DeleteModel(
            name='PostLink',
        ),
    ]
